name: Build system
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build files
      uses: actions/checkout@v4

    - name: Build
      run: |
        cd RozOS
        make install
        make build

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: rozos-build-${{ github.event.inputs.build_type }}-${{ github.run_id }}
        path: |
          RozOS/build/
          RozOS/*.bin
          RozOS/*.img
          RozOS/*.iso
          RozOS/*.o
          RozOS/*.s
          RozOS/*.elf
          RozOS/*.cfg
          RozOS/iso/boot/grub/grub.cfg
          RozOS/*.*
        retention-days: 7

